executable=/project/atlas/users/mveldijk/drellyan_maf/run/condor/mveldijk/condorsub/run_train_888321.sh
JobBatchName=run_train_888321
+JobCategory="short"
+UseOS="el9"
+MaxWallTime=
request_cpus=1
request_memory=16000
log = /project/atlas/users/mveldijk/drellyan_maf/run/run_train_888321_888321.condorlog
output = /project/atlas/users/mveldijk/drellyan_maf/run/run_train_888321_888321.log
error = /project/atlas/users/mveldijk/drellyan_maf/run/run_train_888321_888321.stderr
queue
