executable=/project/atlas/users/mveldijk/higgs_NN_git/run/condor/mveldijk/condorsub/run_train_3512553.sh
JobBatchName=run_train_3512553
+JobCategory="medium"
+UseOS="el9"
+MaxWallTime=
request_cpus=1
request_memory=8000
log = /project/atlas/users/mveldijk/higgs_NN_git/run/run_train_3512553_3512553.condorlog
output = /project/atlas/users/mveldijk/higgs_NN_git/run/run_train_3512553_3512553.log
error = /project/atlas/users/mveldijk/higgs_NN_git/run/run_train_3512553_3512553.stderr
queue
