executable=/project/atlas/users/mveldijk/higgs_NN_git/run/condor/mveldijk/condorsub/run_train_253348.sh
JobBatchName=run_train_253348
+JobCategory="short"
+UseOS="el9"
+MaxWallTime=
request_cpus=1
request_memory=16000
log = /project/atlas/users/mveldijk/higgs_NN_git/run/run_train_253348_253348.condorlog
output = /project/atlas/users/mveldijk/higgs_NN_git/run/run_train_253348_253348.log
error = /project/atlas/users/mveldijk/higgs_NN_git/run/run_train_253348_253348.stderr
queue
